apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubuna-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ubuna.com  # Change to your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ubuna-service  # Adjust service name as needed
            port:
              number: 80